name: CI

on:
  push:
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer
          extensions: mbstring, xml, curl, sqlite, zip

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --force

      - name: Pint (style) - optional
        run: |
          if [ -f vendor/bin/pint ]; then vendor/bin/pint --test; else echo "Pint not installed, skipping."; fi

      - name: Run tests
        run: php artisan test --no-ansi
